version: 2
jobs:
  review:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/docker-ubuntu-ruby-python-npm
    environment:
      repoSite: dev-sunbird/dev-sunbird.github.io
      repoSiteFolder: dev-sunbird.github.io
      repoDocs: dev-sunbird/docs
      qaUrl: qadocs.sunbird.org
      s3Bucket: sunbird-trial
      s3Endpoint: .s3-website.ap-south-1.amazonaws.com
      subdomainPrefixDocs: pr-docs
      subdomainPrefixSite: pr-site
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        command: |
          if [ "$CIRCLE_BRANCH" != "dev" ]
          then
          echo "buildVersion: Site PR - $CIRCLE_PR_NUMBER" >> _config.yml
          else
          echo "buildVersion: Commit" >> _config.yml
          fi
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          chmod +x fetch.sh
          ./fetch.sh
          chmod +x version.sh
          ./version.sh
          bundle exec jekyll build 
      # Deploy to s3 bucket
      - type: shell
        command: |
           cd _site
           if [ "$CIRCLE_BRANCH" != "dev" ]
           then
           aws s3 sync --delete --quiet . s3://$s3Bucket/$subdomainPrefixSite/$CIRCLE_PR_NUMBER
           prData=$(curl -X GET -u $guser:x-oauth-basic https://api.github.com/repos/$repoSite/issues/$CIRCLE_PR_NUMBER)
           userName=$(echo "${prData}" | jq '.user.login')
           contributor=${userName//\"/} 
           siteUrl='http://'$subdomainPrefixSite"-"$CIRCLE_PR_NUMBER"."$qaUrl
           curl \
              -X POST \
              -u $guser:x-oauth-basic \
              -d '{"body": "Hello @'"$contributor"',<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request <br/> - '"$siteUrl"' ."}' \
              https://api.github.com/repos/$repoSite/issues/$CIRCLE_PR_NUMBER/comments
           else
           aws s3 sync --delete --quiet . s3://$s3Bucket/review/
           fi
           
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/docker-ubuntu-ruby-python-npm
    environment:
      repoSite: dev-sunbird/dev-sunbird.github.io
      repoSiteFolder: dev-sunbird.github.io
      repoDocs: dev-sunbird/docs
      qaUrl: qadocs.sunbird.org
      s3Bucket: sunbird-trial
      s3Endpoint: .s3-website.ap-south-1.amazonaws.com
      subdomainPrefixDocs: pr-docs
      subdomainPrefixSite: pr-site
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        command: |
          echo "buildVersion: Release - $CIRCLE_TAG" >> _config.yml
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          chmod +x fetch.sh
          ./fetch.sh
          chmod +x version.sh
          ./version.sh
          bundle exec jekyll build
          
      # Deploy to s3 bucket
      - type: shell
        command: |
           cd _site
           aws s3 sync --delete . s3://$s3Bucket/releases/$CIRCLE_TAG
  prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/docker-ubuntu-ruby-python-npm
    environment:
      repoSite: dev-sunbird/dev-sunbird.github.io
      repoSiteFolder: dev-sunbird.github.io
      repoDocs: dev-sunbird/docs
      qaUrl: qadocs.sunbird.org
      s3Bucket: sunbird-trial
      s3Endpoint: .s3-website.ap-south-1.amazonaws.com
      subdomainPrefixDocs: pr-docs
      subdomainPrefixSite: pr-site
    steps:
      
      #Checkout
      - checkout
          
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - "c3:11:0a:22:15:51:43:8f:70:b8:76:5a:5a:59:07:49"
      #Add User
      - type: shell
        command: |
          git config --global user.email "lakhan_m@tekditechnologies.com"
          git config --global user.name "Lakhan Mandloi"
      
      # Pull Code from staging site
      - type: shell
        command: |
          cd ..
          mkdir downloads
          cd downloads
          aws s3 sync --delete s3://$s3Bucket/releases/$CIRCLE_TAG .
           
      # Deploy to Gitpages
      - type: shell
        command: |
          cd ..
          mkdir deploy
          cd deploy
          git clone git@github.com:$repoSite.git origin/master
          cd $repoSiteFolder
          cp -R .git/ ../
          rm -rf *
          cd ..
          cp -R ../downloads/* $repoSiteFolder/
          cp -R .git/ $repoSiteFolder/
          cd $repoSiteFolder/
          git add -A
          git commit -m "Release - $CIRCLE_TAG"
          git push origin master
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - review
      - staging:
          filters:
            tags:
              only: /^release.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
              - staging
          filters:
            tags:
              only: /^release.*/
            branches:
              ignore: /.*/
      - prod:
          requires:
              - hold
          filters:
            tags:
              only: /^release.*/
            branches:
              ignore: /.*/
